kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: acme-controller
  labels:
    app: acme-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: acme-controller
    spec:
      containers:
      - name: acme-controller
        image: "docker.io/tnozicka/openshift-acme"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: OPENSHIFT_ACME_ACMEURL
          value: "https://acme-staging.api.letsencrypt.org/directory"
        - name: OPENSHIFT_ACME_LOGLEVEL
          value: "8"
        - name: OPENSHIFT_ACME_SELFSERVICENAME
          value: "acme-controller"
